sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
services:
  - docker

install:
  - docker build -t toolisticon/ssl-hostinfo-prometheus-exporter .
  - cd test/setup && docker-compose up -d && cd ../..
  - npm run clean
before_script:
  - pip install --user -r test/setup/test-requirements.txt
script:
   - npm run jasmine-test
   - pytest test/end2end/test_*.py
   - curl -s localhost:9000 | docker exec -i prom/prometheus promtool check metrics
